spring.application.name=customerapp
spring.datasource.url=jdbc:mysql://localhost:3306/customer?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Niru1811

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080